Provider: Yaml
MySql:
  Host: "127.0.0.1"
  Port: "3306"
  Database: "friendsystem"
  User: "root"
  Password: "learn_the_basics"
MongoDB:
  Uri: ""
  Database: "friendsystem"

Commands:
  Friend: "friend"